name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas
  - pip=23.0.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - pip:
    - azureml-defaults==1.53.0
    - azureml-ai-monitoring
    - inference-schema[numpy-support]==1.5.1
    - joblib==1.2.0